### ISSUE TITLE
tap on group in lookup

### ISSUE THREAD

**Issue by knezi** [tuxor1337/firedict#16]
Hi,
I click in Lookup on group button and then on particular group. There appear buttons remove, rename, change members as bellow:
![index](https://cloud.githubusercontent.com/assets/7372304/8041636/f53ab444-0e19-11e5-8adf-e9dd3a342525.png)
Should it appear (with proper size) or not?

**Comment by tuxor1337** [comment]
Ooooh, you are right :D I will fix this.

**Comment by knezi** [comment]
Thanks!
