### ISSUE TITLE
Keyboard does not appear at 'Look up words' screen

### ISSUE THREAD

**Issue by bobcanthelpyou** [tuxor1337/firedict#18]
I am using FireDict 1.5.5 on a Firefox OS 2.0 device.

When clicking on 'Look up ...' the keyboard does not appear.

The only condition to make it appear is to enable the USB storage of Firefox OS but in this mode there are not dictionaries available. When clicking on the menu and go back to the 'Look up words' screen, the keyboard is not available, again.

**Comment by tuxor1337** [comment]
Confirmed. Fix is on the way...
