### ISSUE TITLE
Error while scanning sdcard

### ISSUE THREAD

**Issue by tibtab** [tuxor1337/firedict#25]
Downloaded "factbook" from your site as an example, unzipped it and stored it in sdcard/dictdata (I had to create dictdata manually). But firedict is endless searching for dictionaries.
In the WebIDE I get this:
````
Error while scanning sdcard: (NotFoundError)                wrapper-devicestorage.js:70:0
Path prefix of current storage: null                        wrapper-devicestorage.js:72:0
````

**Comment by tuxor1337** [comment]
1. Which version of Firefox OS are you using?
1. Which device?
1. Does your device have both memory card and internal storage?
1. Did you try both?

**Comment by tibtab** [comment]
ok thanks, I'm using the Open C with fxos 2.2, the problem was the factbook. :)

Another question, which isn't an issue, but which were nice to get answered; I have downloaded some dictionaries which has besides the .dict.dz file, instead of the .idx and .ifo files an .index file. Can also use these dictionaries?

**Comment by tuxor1337** [comment]
Actually, with Firefox OS 2.2, I have even bigger problems - at least using the WebIDE simulator (that's the only way I'm currently testing FireDict). But those problems are gone with the current beta of Firefox OS 2.6...

No, that's the dictd format. FireDict only supports Stardict dictionaries. However, there exist converters for dictd files like `dictd2dic` in the stardict-tools: http://www.simidic.org/wiki/index.php/Install_StarDict-Tools

**Comment by tibtab** [comment]
ok thanks for your answer. Which problems do you have with fxos 2.2? Maybe I could test, if I'm experiencing the same. I'm not directly using fxos 2.2. I'm using a mozfr community build for the european Open C. I tried the mozfr 2.6 community build for some days, but I had so many problems with it, that I went back to 2.2

**Comment by tuxor1337** [comment]
If you are fine with most dictionaries, then the error that I'm getting doesn't affect you. Running FireDict in the Firefox OS 2.2 simulator will not load any dictionaries at first start. It has to do with the IndexedDB API, but I don't think it's worth diving into this ;)

Okay, since your problem is solved, I'm closing this.
