### ISSUE TITLE
App hangs forever when loading dictionaries during startup

### ISSUE THREAD

**Issue by trenchcode** [tuxor1337/firedict#6]
The app hangs forever when loading dictionaries during startup. Others wrote this in comments in the Marketplace, too.

I tracked the problem to commit https://github.com/tuxor1337/firedict/commit/03432c64f536acaa672085623a6e93a133831443 ("speed up file system scan and include all sdcard storages "). This commit breaks the app for me. The previous commit https://github.com/tuxor1337/firedict/commit/c1499b6364adba37ee4871f82e7d1e3ca18f827b works.

To test, I installed the latest commit https://github.com/tuxor1337/firedict/commit/08140f1f4c837a2f9eb36ad4aa939d2bcaaf2606 and simply reverted the changes in js/app.js introduced in the breaking commit https://github.com/tuxor1337/firedict/commit/03432c64f536acaa672085623a6e93a133831443. Now the app loads without problems, but I don't know if your changes to 'dictWorker.addListener' had any other side-effects. If not, you could revert the commit https://github.com/tuxor1337/firedict/commit/03432c64f536acaa672085623a6e93a133831443 to make the app usable again.

**Comment by tuxor1337** [comment]
Which phone and which ROM and version of Firefox OS are you using? Are you using an sdcard or the internal storage? Would it be possible to get some debugging output from Mozilla's web-IDE (built into Firefox for Desktop)?

I'm using this app without issues on a daily basis on my Android 4.4 phone. A friend uses it with Firefox OS 1.3 on a ZTE Open C. Additionally, I'm testing with a Firefox OS 1.3 emulator.

Am 22. Januar 2015 10:49:17 MEZ, schrieb trenchcode <notifications@github.com>:

**Comment by trenchcode** [comment]
Found the bug. It's the typo in js/app.js (https://github.com/tuxor1337/firedict/commit/08140f1f4c837a2f9eb36ad4aa939d2bcaaf2606) line 205 `p2 = p2.prelace(/^\/+/, "");`

Should be `p2.replace` and everything will work fine for many of your users.

Thanks for the nice app!

**Comment by tuxor1337** [comment]
Great, thanks! I will correct the typo and publish the fixed version to the marketplace asap.
